name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  # For the CI.
  SECRET: "TEST_SECRET"
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: password
  POSTGRES_DB: testdb
  DATABASE_URL: "postgresql+asyncpg://testuser:password@localhost:5432/testdb"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install frontend dependencies
      run: npm install

    - name: Install backend dependencies
      uses: astral-sh/setup-uv@v6

    - name: Run the CI
      run: npx rust-just@latest ci
